name: room_finder_flutter
description: A new Flutter project.

version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Base
  nb_utils: ^7.0.4
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.0

  # STATE MANAGEMENT
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  flutter_secure_storage: ^4.2.1
  image_picker: ^1.1.2

dependency_overrides:
  intl: ^0.19.0
  http: ^1.2.2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: ^2.6.1
  build_runner: ^2.4.12
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true

  assets:
    - images/roomFinding/
    - images/app/
    - images/app/placeholder.png
